FROM rustembedded/cross:i686-unknown-linux-musl

RUN apt-get update
RUN apt-get install -y build-essential pkg-config libx11-dev musl-tools libfontconfig libfontconfig1-dev fontconfig libfreetype6 expat libc6-dev